spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/vocavoca
    username: user1234
    password: password1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  messages:
    basename: messages,errors


server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800



logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.apache.coyote.http11: debug
